#!/usr/bin/php
<?php
	/* @author JasonKurtz 
	 * @version 0.1 
	 * @description A simple PHP script to rename extensions of a files in the current directory. 
	 * @example ./fix-ext JPG jpg ; This will rename <file>.JPG to <file>.jpg in the current directory 
	 */ 
	if (!isset($argv[1]) || !isset($argv[2]))
		die("Syntax: ./fix-ext <old extension> <new extension>\n"); 
	$oldext = $argv[1]; 
	$newext = $argv[2]; 
	$dir = getcwd(); 
	$handle = opendir($dir); 
	while (($file = readdir($handle)) !== false) {
		$fa = explode(".", $file); 
		$ext = end($fa); 
		array_pop($fa); 
		if ($file != "." && $file != ".." & $ext == $oldext) {
			$command = sprintf("mv %s %s\n", $file, implode("", $fa) . "." . $newext); 
			echo $command; 
			exec($command); 
		}
	}
	closedir($handle); 
	echo "\n"; 
?>